### ISSUE TITLE
weaponswap configflag deactivates vehicle weapons

### ISSUE THREAD

**Issue by KyuubiDDragon** [altmp/altv-issues#1009]
**Client/server version**
newest release (4.0.0) 

**Current behavior**
The new config flag disable the vehicle weapon like the firetruck water cannon.

**Expected behavior**
Dont deactivate them

**Steps to reproduce**
activate the weapon swap configflag

**Context (environment)**
The following: Added configflag to disable weaponswap if weapon is empty

The new config flag disable the vehicle weapon like the firetruck water cannon.

If we disable this flag, it works without problems.

**Possible solution**

**Comment by LeonMrBonnie** [comment]
Please follow the issue template.

**Comment by Doxoh** [comment]
Confirmed too with native.setPedConfigFlag(this.localPlayer.scriptID, 48, true);

**Comment by Kingwolfi** [comment]
confirmed

**Comment by Doxoh** [comment]
Is it possible to fix this in the next version?
It was a nice feature for us.

**Comment by FabianTerhorst** [comment]
We will try to fix it for the 7.0 update.

**Comment by C0kkie** [comment]
Will be fixed in next rc build

**Comment by Doxoh** [comment]
It's fixed, but a ped config flag has the same problem, maybe it's possible to fix theirs too.  #1133

**Comment by mrgharabaghi** [comment]
Actually, this is not the optimal way to achieve this.
@KyuubiDDragon
```js
alt.setInterval(() => {
    let scriptID = alt.Player.local.scriptID;
    let weapon = native.getCurrentPedWeapon(scriptID);
    if (weapon[0] && native.isPedShooting(scriptID) && native.getAmmoInPedWeapon(scriptID, weapon[1]) == 1) {
        native.taskSwapWeapon(scriptID, false);
        native.setPedAmmo(scriptID, weapon[1], 0);
    }
}, 10);
```

**Comment by Doxoh** [comment]
Bug confirmed again with version 8.8

**Comment by FabianTerhorst** [comment]
Fixed next release.

**Comment by Doxoh** [comment]
Bug is back with 9.3
In RC its worked but now its broken again

**Comment by YannBCF** [comment]
It's only occuring when you don't shuffle into the weapon seat.

**Comment by C0kkie** [comment]
Fixed in next dev
