### ISSUE TITLE
Entity streaming distance bug

### ISSUE THREAD

**Issue by Lekenthu** [altmp/altv-issues#2049]
### Description of the problem

The streaming distance is not working properly. It is also set to 200 in the server configuration, the streamingDistance getter returns 200, but my vehicle is still visible up to ~400 distance. (It has a scriptID until then.)
Also, if I set the streamingDistance setter (server-side) to, for example, 1000, it will not work.

The config file value is returned correctly by the server:
SRUN command: alt.getServerConfig().streamingDistance 
SRUN result: 200 

### Reproduction steps

1. Set the streaming distance to 200, for example.
2. Create vehicle.
3. Let's go about 300 distances.
4. The vehicle is still visible.

### Expected behaviour

The value specified in the configuration should actually be the default value for the entity. And with the streamingDistance setter, I want to set any value for a given entity. (For example: 2000)

### Operating system

Windows 11

### Version

#15.0-dev730

### Reproduction tested

- [X] I confirm that I have made sure that this issue is also present on the newest dev version

**Comment by MyHwu9508** [comment]
Can confirm this on latest dev. 
When using streamingdistance 500 the vehicles only become visible with < 240m distance

**Comment by FabianTerhorst** [comment]
Fixed in latest dev.

**Comment by MyHwu9508** [comment]
Issue persists for clientside created vehicles using LocalVehicle constructor

**Comment by FabianTerhorst** [comment]
no this specific bug was only in serverside code.
