### ISSUE TITLE
Dead players not visible when someone come into streaming range

### ISSUE THREAD

**Issue by UL-Liam** [altmp/altv-issues#220]
We have the problem, that every time when someone dies and someone new comes into his streaming range, the new one can't see the dead person. Also when the killer drives out of the Range and back, the dead one is not visible, but he still lies on the same position. Like in that video: https://plays.tv/video/5d45c954a7fd07bdf9/help

(We are on the beta)

## Expected Behavior
The player should be visible, when someone new comes into the Range xD

## Current Behavior
The player is not visible

## Steps to Reproduce

1.
1.
1.
1.

## Context (Environment)
We are developing a Roleplay Server named "Unknown-Life", and there we need to fix this problem, because the Medics should see the dead people, so that they can revive them xD

**Comment by UL-Liam** [comment]
Edit: The player-model is not loaded for the new person. (If you activate Nametags, it isn't visible too). It's not only invisible

**Comment by FabianTerhorst** [comment]
have you tried loading the player freeroam models or the models the player has on start of client script with alt.loadModel?

**Comment by Stuyk** [comment]
Can confirm that this is an issue.

Kill a player; go out of stream range then teleport to that player. They are not synchronized properly on returning. After spawning the dead player they are back to normal.

**Comment by FabianTerhorst** [comment]
You should revive the player and set it to ragdoll on death.

**Comment by Stuyk** [comment]
> You should revive the player and set it to ragdoll on death.

This is a valid solution. Thank you.
If the team wants to maybe they can implement a solution that auto-respawns on death and has a server side handle for forcing players into rag doll. Thanks again.

**Comment by bozoweed** [comment]
up that ontinue to bug plese fix dead body for real

**Comment by FabianTerhorst** [comment]
you have to spawn the player after death.

**Comment by bozoweed** [comment]
i don't like this solution
because i made some check about deadentity
so if i respawn him is not dead so my check is broken
or be spawn you mean juste use Iplayer spawn but not give him heal ? so steal dead entity ?

**Comment by vadzz-dev** [comment]
Is it still actual?

**Comment by c0nnex** [comment]
can we reopen this? It's really a bummer that dead players are not streamed in at all.

**Comment by Lhoerion** [comment]
@c0nnex Provide some confirmation on this from newest builds and I'll reopen it

**Comment by c0nnex** [comment]
We have tested this extensively on Saturday with current release (build #1071)

Following observations:

a) Player dies with all other players in streaming range:
All fine. Player lies on ground (repeatedly triggered "dead" animation playing)

b) Player dies with some players OUT of streaming range:
Players comming into the streaming range will NOT see the dead player untill he reconnects or respawns. There is no "obejctCreated" event raised for the dead player

c) Player dies with all players in streaming range, upon death a "spawn" is called for the dead player and "dead" animation triggered 
All players see the dead player, but animation starts for about 1 second, then the ped will be strechted straight up in slowmotion and keep standing (while the dead player itself still sees  the dead animation)

d) Player dies with some players out of streaming range, upon death a "spawn" is called for the dead player and "dead" animation triggered 
All players see the formerly dead player, but instead of animation he is standing upright

(c & d) also tested with ragdolling. Same result.

**Comment by FabianTerhorst** [comment]
Afaik this is a gta bug and servers needs to workaround it. Maybe player ped should just despawn after dead?

**Comment by btx78000** [comment]
don't know if it can help someone, but in my test the dead players have a wrong position in this state. clientside, after checking the position of the dead player, i got ~70meters under the real positions, resetting positions for clients from server positions looks like its working or just respawning it serverside ( but its very weird for rp servers )

**Comment by Lhoerion** [comment]
We've tested this recently on #[1239](https://discord.com/channels/371265202378899476/528297438348574741/719017027368386652) and we haven't encountered any visibility problems apart from minor discrepancies with victim position being different for than killer than witnesses.

**Comment by Lhoerion** [comment]
No response from the author

Issue closed because of the specified reasons.
Feel free to respond back here, if you think that it should be reopened.

**Comment by yoranjj** [comment]
Can we re-open this as it is still an issue?

> don't know if it can help someone, but in my test the dead players have a wrong position in this state. clientside, after checking the position of the dead player, i got ZPos ~70meters under the real positions, resetting positions for clients from death saved position(in death event ) in server positions looks like its working or just respawning it serverside ( but its very weird for rp servers )

> We've tested this recently on #[1239](https://discord.com/channels/371265202378899476/528297438348574741/719017027368386652) and we haven't encountered any visibility problems apart from minor discrepancies with victim position being different for the killer than witnesses.

The two quoted replies above sum up what the issue is and a potential workaround (which isn't very practical).

**Comment by martonp96** [comment]
Looks like the same problem as https://github.com/altmp/altv-issues/issues/224

**Comment by martonp96** [comment]
The latest dev build (dev/2.1-dev7) should fix this issue, please try it and provide feedback if you can.

**Comment by yoranjj** [comment]
Still having the same issue on my end (dev/2.1-dev7). Dead players "fall" when they are streamed in for anybody which ends up setting their body at the nearest spawn node on the road or on a roof (as shown in the screenshot below).

![e6e9f0978e8fee6b8a9f9acbe9c3be056e5c0eab728ca379](https://user-images.githubusercontent.com/17703007/97979252-20c2b880-1dcf-11eb-86e7-f12a7b2ef6ed.jpg)

**Comment by Heady20006** [comment]
we are using 2.1-dev7 and the issue is already existing

**Comment by C0kkie** [comment]
Its fixed since dev/2.1-dev12
