### ISSUE TITLE
Voice Chat example broken

### ISSUE THREAD

**Issue by phumberdroz** [altmp/altv-issues#432]
Voice chat example resource is broken. 
`alt.createVoiceChannel` get s called which is not the way to create a channel it should be `new alt.VoiceChannel`
## Expected Behavior

Example resource works out of the box
## Current Behavior

does not work

**Comment by martonp96** [comment]
This was fixed in example resources repo.
https://github.com/altmp/altv-example-resources/blob/master/voice/server/index.mjs

**Comment by Quantum2707** [comment]
Cheers,

I just downloaded from the official altv page today and there the voice-chat example ist still broken.

Best Regards.

**Comment by C0kkie** [comment]
What exactly is there broken?

**Comment by LeonMrBonnie** [comment]
You probably just didn't enable the voice chat in your server cfg

**Comment by Quantum2707** [comment]
Nah, I downloaded the example files from the official altv page and there seems to be the old version linked. So the example in this git repo works but the old one on the official downloads page is still the same which was missing the new statement. Noticed it is older cause I downloaded/cloned both this git repo and the altv examples from the download page.

Cheers.

**Comment by Quantum2707** [comment]
Eeeeer, I am not sure if it is that the change states in this issue right here is still not in release? I got the release build incl. examples - but its a 1 year old issue. Maybe double check if just the files from the downlods page are outdated. 
For Downloading the server incl. examples I ticked all except C# Module, Branch = Release and Server = Windows.

Hope that helps

**Comment by C0kkie** [comment]
Show your server.cfg @Quantum2707

**Comment by Quantum2707** [comment]
I am not using it anymore, but as I tried the settings were the same except of the resources array

`name: 'WireV-RP.de Hardcore Roleplay - LOCAL TEST'
host: 0.0.0.0
port: 7788
players: 128
#password: ultra-password
announce: false
#token: YOUR_TOKEN
gamemode: Roleplay
website: wirev-rp.de
language: de
description: 'alt:V Sample Server'
modules: [ js-module ]
resources: [
  example
]
voice: {
    bitrate: 64000
}
debug: true`

**Comment by Lhoerion** [comment]
Wrong example resources were served, when they should be from this repo https://github.com/altmp/altv-example-resources.
It's fixed now.
