### ISSUE TITLE
C# | AltAsync | Player Console "quit" command, close game and "timeout" didn't remove player from server 

### ISSUE THREAD

**Issue by Revyn112** [altmp/altv-issues#742]
**Client/server version**
`Build #2.2-dev1, branch dev`

**Current behavior**
Using "quit" command in console, closing the game or getting a timeout didn't remove the player from the server.
Event PlayerDisconnect and PlayerRemove aren't called.
Player is still visible and stay in server player pool, still after reconnect..

Using "reconnect" command works like it should be. (Events got fired)

**Expected behavior**
Remove player properly from server.

**Steps to reproduce**
1. Use ServerEvent PlayerDisconnect / PlayerRemove to verify disconnect / remove.
2. Join on Server and use "quit" command in console.
3. Verify if ServerEvents get called

**Context (environment)**
Querying player pool leds to misleading behavior with non-existent player (e.g. calculate life cycle system).

**Comment by C0kkie** [comment]
Can't confirm it.

https://img.c0kkie.de/c0kkie_11-12-2020_01-15-59.png

on 2.2-dev1

**Comment by C0kkie** [comment]
I cant confirm it on #2.2-dev1

https://img.c0kkie.de/c0kkie_11-12-2020_01-19-25.png

**Comment by Revyn112** [comment]
> 
> 
> I cant confirm it on 2.2-dev1
> 
> https://img.c0kkie.de/c0kkie_11-12-2020_01-19-25.png

can you confirm for "quit" command too?

**Comment by C0kkie** [comment]
i used the quit command yes

**Comment by Revyn112** [comment]
This is strange, can reproduce this 100% of time.
When using reconnect, events get fired as they should.

**Comment by C0kkie** [comment]
Did you try on a empty gamemode? If not try it there

**Comment by Revyn112** [comment]
> 
> 
> Did you try on a empty gamemode? If not try it there

Are using the Events with AltAsync on latest package?

**Comment by C0kkie** [comment]
I dont use AltAsync

**Comment by FabianTerhorst** [comment]
Please test again on latest rc.

**Comment by Revyn112** [comment]
> 
> 
> Please test again on latest rc.

Tested in 2.2rc-4, still not working

**Comment by FabianTerhorst** [comment]
Can you provide a small resource to reproduce?

**Comment by Revyn112** [comment]
After latest test the event get fired after six minutes.

**Comment by FabianTerhorst** [comment]
Afaik the Connection Code will be refactored  and that will be fixed by this. So the 6 Minuten are currently by Design.

**Comment by Revyn112** [comment]
This bug still exist in release4.0

**Comment by Revyn112** [comment]
This bug still exist in release6.4

**Comment by FabianTerhorst** [comment]
Fixed in next update.

**Comment by Revyn112** [comment]
@FabianTerhorst starting testing the release client today, we can't confirm its not solved.

**Comment by FabianTerhorst** [comment]
You have to Test with RC Branch.

**Comment by Revyn112** [comment]
> You have to Test with RC Branch.

Sorry I meant the Release Candidate.

**Comment by Revyn112** [comment]
@FabianTerhorst  Sorry I meant the Release Candidate.

**Comment by FabianTerhorst** [comment]
Timeout can be 15 minutes or higher on quit.

**Comment by Revyn112** [comment]
@FabianTerhorst so to get it right, the problem itself is not resolved here?
So i have still "phantom" players which didn't get removed until some time passed by and have them still visible for all players on the server.

**Comment by FabianTerhorst** [comment]
The initial issue was that the disconnect event wasnt called at all after specific circumstances.

**Comment by Revyn112** [comment]
@FabianTerhorst btw in the initial issue this behaviour was mentioned:

```
Using "quit" command in console, closing the game or getting a timeout **didn't remove the player from the server**.
Event PlayerDisconnect and PlayerRemove aren't called.
**Player is still visible** and stay in server player pool, still after reconnect.
```
