### ISSUE TITLE
you can't destroy a webview inside a webview event handler

### ISSUE THREAD

**Issue by Sushi1337** [altmp/altv-issues#748]
**Client/server version**
`Build #dev/2.2-dev5, branch dev (and propably rc)`

**Current behavior**
destroying a webview inside a webview event handler causes a clientcrash

**Expected behavior**
the webview should be destroyed without crash (as it currently does on release-branch)

**Steps to reproduce**
- create a webview
- inside of the webview do something like alt.emit("Close")
- outside the webview catch the close event and destroy the webview

**Context (environment)**
In our case we have a cloth store where players can close it by pressing backspace. Doing this triggers a webview.destroy(); outside of the webview.
This worked fine in release-branch, but causes a clientcrash in dev currently.
**Vektor asked me to open this issue with this exact title so it can be fixed. He also has a crashdump which shows this bug.**

**Possible solution**
delaying the destruction with a 1sec timeout or by using nextTick prevents the client from crashing

**Comment by martonp96** [comment]
Fixed in 2.2-dev7

**Comment by lsvMoretti** [comment]
This is still an issue. I require to delay for 1000ms for the close event.

This doesn't happen to every player, but doing the following has fixed it.

`if (bankView != undefined) {
            alt.setTimeout(() => {
                bankView.destroy();
                bankView = undefined;
            }, 1100);
        }`
